host = "127.0.0.1:5556"
#data_position = ""
api_address = "https://survey-api.cmlmuf.org"

[[problems]]
id = 1
is_required = true
question = "邮箱（尽量用proton、tuta邮箱或谷歌邮箱）"

[[problems]]
id = 2
is_required = true
question = "电报ID以及链接（注明是否使用国外手机号，若无ID请填昵称）"

[[problems]]
id = 3
is_required = true
question = "职业（注明是否在工厂，学生最好说明年级）"

[[problems]]
id = 4
is_required = true
question = "每周上线频率和可参与活动的时长"

[[problems]]
id = 5
is_required = true
question = "读过哪些原著"

[[problems]]
id = 6
is_required = true
question = "有无在墙内外参加别的组织或者活动"

[[problems]]
id = 7
is_required = true
question = "使用什么翻墙软件"

[[problems]]
id = 8
is_required = true
question = "是否有专用墙外活动的非华为设备，翻墙设备上有无国产软件"

[[problems]]
id = 9
is_required = true
question = "分析当今中国的社会性质，如何看待“中帝论”"

[[problems]]
id = 10
is_required = true
question = "如何区分社会主义革命与资产阶级民主运动，如何看待暴力革命与议会斗争"

[[problems]]
id = 11
is_required = true
question = "对国家资本主义的看法"

[[problems]]
id = 12
is_required = true
question = "对先锋队理论的看法"

[[problems]]
id = 13
is_required = true
question = "对托洛茨基主义以及一国建成社会主义的看法"

[[problems]]
id = 14
is_required = true
question = "资本能够增殖的秘密在于哪里，与劳动力有何关系"

[[problems]]
id = 15
is_required = true
question = "如何评价“按劳分配”"

[[problems]]
id = 16
is_required = true
question = "对儒法斗争的看法"

[[problems]]
id = 17
is_required = true
question = "融工的重要性"

[[problems]]
id = 18
is_required = true
question = "经济斗争与政治灌输的关系"

[[problems]]
id = 19
is_required = true
question = "线上工作与线下工作的关系"

[[problems]]
id = 20
is_required = true
question = "如何看待知识分子和脑力劳动者"

[[problems]]
id = 21
is_required = true
question = "如何看待流氓无产阶级"

[[problems]]
id = 22
is_required = true
question = "对于民主集中制的理解"

[[problems]]
id = 23
is_required = true
question = "请说说鞍钢宪法的进步性"

[[problems]]
id = 24
is_required = true
question = "无产阶级文化大革命是一项领导者错误发动的运动吗，具体说明"

[[problems]]
id = 25
is_required = true
question = "自己进厂融工的主观准备和客观条件"
